### PR TITLE
2.6 compatibility

### PR DESCRIPTION
**Pull request by jonmifsud**
Rename class so that the Date Time Calendar looks good in Symphony 2.6, due to a class conflict.

### CODE REVIEW

**Comment by nilshoerrmann** [comment]
Thanks, Jonathan!
@nitriques: Would you mind having a look at this? Thanks!

**Comment by nitriques** [comment]
Yes!

@jonmifsud I would like to reuse as much code from the core as possible. So we would only have the overrides in our code base. I think there is a possible 90% reuse in this case.

If you do not have the time to do it, I will in the near future. I'll leave this PR opened as a reminder.

**Comment by jonmifsud** [comment]
@nitriques  Sure, agree with you the fix was something quick to get the extension running! At this time I don't have a lot of time to play around, as you've noticed I've got a lot of loose ends running around. + a few more extensions in the works. Maybe after the turn of the month I'll have some time to look into it.

**Comment by nitriques** [comment]
Great!

**Comment by nitriques** [comment]
Hey @johannahoerrmann sorry for the delay, but I did tried your PR today. Should it be 100% ok ? Or just better ?

Cuz my setup is still badly broken.

**Pull request merged**
